// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

///////////////////// SCREENS ////////////////////
#include "ui_StartupScr.h"
#include "ui_SingleScr.h"
#include "ui_SettingsScr.h"
#include "ui_DashDisplay.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// FONTS
LV_FONT_DECLARE( ui_font_GilBig);
LV_FONT_DECLARE( ui_font_GilMedium);
LV_FONT_DECLARE( ui_font_GilSm);
LV_FONT_DECLARE( ui_font_SeveSegLg);
LV_FONT_DECLARE( ui_font_SeveSegSm);
LV_FONT_DECLARE( ui_font_SevenSegLbl);
LV_FONT_DECLARE( ui_font_SevenSegMd);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
