// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_DASHDISPLAY_H
#define UI_DASHDISPLAY_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_DashDisplay
extern void ui_DashDisplay_screen_init(void);
extern void ui_DashDisplay_screen_destroy(void);
extern void ui_event_DashDisplay( lv_event_t * e);
extern lv_obj_t *ui_DashDisplay;
extern lv_obj_t *ui_LambdaArc;
extern lv_obj_t *ui_ThrottleArc;
extern lv_obj_t *ui_rpmLbl;
extern lv_obj_t *ui_groupContainer;
extern lv_obj_t *ui_vbar;
extern lv_obj_t *ui_boostLbl;
extern lv_obj_t *ui_boostValLbl;
extern lv_obj_t *ui_boostmaxValLbl;
extern lv_obj_t *ui_aitLbl;
extern lv_obj_t *ui_aitValLbl;
extern lv_obj_t *ui_aitmaxValLbl;
extern lv_obj_t *ui_maxLbl;
extern lv_obj_t *ui_speedLbl;
extern lv_obj_t *ui_ShiftUpLbl;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

