// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *uic_clock_unit;
lv_obj_t *uic_clock_value;
lv_obj_t *uic_clock_name;
lv_obj_t *uic_clock;
lv_obj_t *uic_torque_unit;
lv_obj_t *uic_torque_value;
lv_obj_t *uic_torque_power;
lv_obj_t *uic_torque;
lv_obj_t *uic_ignition_unit;
lv_obj_t *uic_ignition_value;
lv_obj_t *uic_ignition_name;
lv_obj_t *uic_ignition;
lv_obj_t *uic_APC_unit;
lv_obj_t *uic_APC_value;
lv_obj_t *uic_APC_name;
lv_obj_t *uic_APC;
lv_obj_t *uic_speed_unit;
lv_obj_t *uic_speed_value;
lv_obj_t *uic_speed_name;
lv_obj_t *uic_speed;
lv_obj_t *uic_throttle_unit;
lv_obj_t *uic_throttle_value;
lv_obj_t *uic_throttle_name;
lv_obj_t *uic_throttle;
lv_obj_t *uic_tach_shiftup;
lv_obj_t *uic_tach_unit;
lv_obj_t *uic_tach_value;
lv_obj_t *uic_tach_name;
lv_obj_t *uic_tach;
lv_obj_t *uic_lambda_unit;
lv_obj_t *uic_lambda_value;
lv_obj_t *uic_lambda_name;
lv_obj_t *uic_lambda;
lv_obj_t *uic_ait_unit;
lv_obj_t *uic_ait_value;
lv_obj_t *uic_ait_name;
lv_obj_t *uic_ait;
lv_obj_t *uic_cts_unit;
lv_obj_t *uic_cts_value;
lv_obj_t *uic_cts_name;
lv_obj_t *uic_cts;
lv_obj_t *uic_boost_unit;
lv_obj_t *uic_boost_value;
lv_obj_t *uic_boost_name;
lv_obj_t *uic_voltmeter_unit;
lv_obj_t *uic_voltmeter_value;
lv_obj_t *uic_voltmeter_name;
lv_obj_t *uic_voltmeter;
lv_obj_t *uic_SingleScr;
lv_obj_t *ui_SingleScr = NULL;lv_obj_t *ui_voltmeter = NULL;lv_obj_t *ui_boost = NULL;lv_obj_t *ui_cts = NULL;lv_obj_t *ui_ait = NULL;lv_obj_t *ui_lambda = NULL;lv_obj_t *ui_tach = NULL;lv_obj_t *ui_shiftup = NULL;lv_obj_t *ui_throttle = NULL;lv_obj_t *ui_speed = NULL;lv_obj_t *ui_APC = NULL;lv_obj_t *ui_ignition = NULL;lv_obj_t *ui_torque = NULL;lv_obj_t *ui_clock = NULL;
// event funtions
void ui_event_SingleScr( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_DashDisplay, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 150, 0, &ui_DashDisplay_screen_init);
}
}

// build funtions

void ui_SingleScr_screen_init(void)
{
ui_SingleScr = lv_obj_create(NULL);
lv_obj_set_scrollbar_mode(ui_SingleScr, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_scroll_dir(ui_SingleScr, LV_DIR_HOR);
lv_obj_set_scroll_snap_x(ui_SingleScr, LV_SCROLL_SNAP_END);
lv_obj_set_flex_flow(ui_SingleScr,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_SingleScr, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_set_style_bg_color(ui_SingleScr, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SingleScr, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_voltmeter = ui_Gauge_create(ui_SingleScr);
lv_obj_set_x( ui_voltmeter, 124 );
lv_obj_set_y( ui_voltmeter, 244 );

lv_obj_set_x( ui_comp_get_child(ui_voltmeter, UI_COMP_GAUGE_VALUE), -25 );
lv_obj_set_y( ui_comp_get_child(ui_voltmeter, UI_COMP_GAUGE_VALUE), 0 );
lv_label_set_text(ui_comp_get_child(ui_voltmeter, UI_COMP_GAUGE_VALUE),"12.1");

ui_boost = ui_Gauge_create(ui_SingleScr);
lv_obj_set_x( ui_boost, 124 );
lv_obj_set_y( ui_boost, 244 );

lv_label_set_text(ui_comp_get_child(ui_boost, UI_COMP_GAUGE_NAME),"BOOST");

lv_label_set_text(ui_comp_get_child(ui_boost, UI_COMP_GAUGE_VALUE),"0.8");

lv_label_set_text(ui_comp_get_child(ui_boost, UI_COMP_GAUGE_UNIT),"BAR");

ui_cts = ui_Gauge_create(ui_SingleScr);
lv_obj_set_x( ui_cts, 124 );
lv_obj_set_y( ui_cts, 244 );

lv_label_set_text(ui_comp_get_child(ui_cts, UI_COMP_GAUGE_NAME),"coolant");

lv_label_set_text(ui_comp_get_child(ui_cts, UI_COMP_GAUGE_VALUE),"92");

lv_label_set_text(ui_comp_get_child(ui_cts, UI_COMP_GAUGE_UNIT),"C");

ui_ait = ui_Gauge_create(ui_SingleScr);
lv_obj_set_x( ui_ait, 124 );
lv_obj_set_y( ui_ait, 244 );

lv_label_set_text(ui_comp_get_child(ui_ait, UI_COMP_GAUGE_NAME),"INTAKE AIR");

lv_label_set_text(ui_comp_get_child(ui_ait, UI_COMP_GAUGE_VALUE),"47");

lv_label_set_text(ui_comp_get_child(ui_ait, UI_COMP_GAUGE_UNIT),"C");

ui_lambda = ui_Gauge_create(ui_SingleScr);
lv_obj_set_x( ui_lambda, 124 );
lv_obj_set_y( ui_lambda, 244 );

lv_label_set_text(ui_comp_get_child(ui_lambda, UI_COMP_GAUGE_NAME),"o2");

lv_label_set_text(ui_comp_get_child(ui_lambda, UI_COMP_GAUGE_VALUE),"0.8");

lv_label_set_text(ui_comp_get_child(ui_lambda, UI_COMP_GAUGE_UNIT),"L");

ui_tach = ui_Gauge_create(ui_SingleScr);
lv_obj_set_x( ui_tach, 124 );
lv_obj_set_y( ui_tach, 244 );

lv_label_set_text(ui_comp_get_child(ui_tach, UI_COMP_GAUGE_NAME),"");

lv_label_set_text(ui_comp_get_child(ui_tach, UI_COMP_GAUGE_VALUE),"3425");

lv_label_set_text(ui_comp_get_child(ui_tach, UI_COMP_GAUGE_UNIT),"RPM");

ui_shiftup = lv_obj_create(ui_tach);
lv_obj_set_width( ui_shiftup, 100);
lv_obj_set_height( ui_shiftup, 100);
lv_obj_set_x( ui_shiftup, 0 );
lv_obj_set_y( ui_shiftup, -150 );
lv_obj_set_align( ui_shiftup, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_shiftup, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_shiftup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_shiftup, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_shiftup, lv_color_hex(0xDEB600), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_shiftup, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_move_to_index(ui_shiftup,3);

ui_throttle = ui_Gauge_create(ui_SingleScr);
lv_obj_set_x( ui_throttle, 124 );
lv_obj_set_y( ui_throttle, 244 );

lv_label_set_text(ui_comp_get_child(ui_throttle, UI_COMP_GAUGE_NAME),"TPS");

lv_label_set_text(ui_comp_get_child(ui_throttle, UI_COMP_GAUGE_VALUE),"13.6");

lv_label_set_text(ui_comp_get_child(ui_throttle, UI_COMP_GAUGE_UNIT),"%	");

ui_speed = ui_Gauge_create(ui_SingleScr);
lv_obj_set_x( ui_speed, 124 );
lv_obj_set_y( ui_speed, 244 );

lv_label_set_text(ui_comp_get_child(ui_speed, UI_COMP_GAUGE_NAME),"--");

lv_label_set_text(ui_comp_get_child(ui_speed, UI_COMP_GAUGE_VALUE),"13.6");

lv_label_set_text(ui_comp_get_child(ui_speed, UI_COMP_GAUGE_UNIT),"kph");

ui_APC = ui_Gauge_create(ui_SingleScr);
lv_obj_set_x( ui_APC, 124 );
lv_obj_set_y( ui_APC, 244 );

lv_label_set_text(ui_comp_get_child(ui_APC, UI_COMP_GAUGE_NAME),"APC");

lv_label_set_text(ui_comp_get_child(ui_APC, UI_COMP_GAUGE_VALUE),"0");

lv_label_set_text(ui_comp_get_child(ui_APC, UI_COMP_GAUGE_UNIT),"%	");

ui_ignition = ui_Gauge_create(ui_SingleScr);
lv_obj_set_x( ui_ignition, 124 );
lv_obj_set_y( ui_ignition, 244 );

lv_label_set_text(ui_comp_get_child(ui_ignition, UI_COMP_GAUGE_NAME),"TIMING");

lv_label_set_text(ui_comp_get_child(ui_ignition, UI_COMP_GAUGE_VALUE),"13.6");

lv_label_set_text(ui_comp_get_child(ui_ignition, UI_COMP_GAUGE_UNIT),"deg");

ui_torque = ui_Gauge_create(ui_SingleScr);
lv_obj_set_x( ui_torque, 124 );
lv_obj_set_y( ui_torque, 244 );

lv_label_set_text(ui_comp_get_child(ui_torque, UI_COMP_GAUGE_NAME),"0");
ui_object_set_themeable_style_property(ui_comp_get_child(ui_torque, UI_COMP_GAUGE_NAME), LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Green);
ui_object_set_themeable_style_property(ui_comp_get_child(ui_torque, UI_COMP_GAUGE_NAME), LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Green);
lv_obj_set_style_text_font(ui_comp_get_child(ui_torque, UI_COMP_GAUGE_NAME), &ui_font_SevenSegMd, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_label_set_text(ui_comp_get_child(ui_torque, UI_COMP_GAUGE_VALUE),"0");
lv_obj_set_style_text_font(ui_comp_get_child(ui_torque, UI_COMP_GAUGE_VALUE), &ui_font_SevenSegMd, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_label_set_text(ui_comp_get_child(ui_torque, UI_COMP_GAUGE_UNIT),"HP/Nm");

ui_clock = ui_Gauge_create(ui_SingleScr);
lv_obj_set_x( ui_clock, 124 );
lv_obj_set_y( ui_clock, 244 );

lv_label_set_text(ui_comp_get_child(ui_clock, UI_COMP_GAUGE_NAME),"CLOCK");

lv_label_set_text(ui_comp_get_child(ui_clock, UI_COMP_GAUGE_VALUE),"7:23");

lv_label_set_text(ui_comp_get_child(ui_clock, UI_COMP_GAUGE_UNIT),"pm");

lv_obj_add_event_cb(ui_SingleScr, ui_event_SingleScr, LV_EVENT_ALL, NULL);
uic_SingleScr = ui_SingleScr;
uic_voltmeter = ui_voltmeter;
uic_voltmeter_name = ui_comp_get_child(ui_voltmeter, UI_COMP_GAUGE_NAME);
uic_voltmeter_value = ui_comp_get_child(ui_voltmeter, UI_COMP_GAUGE_VALUE);
uic_voltmeter_unit = ui_comp_get_child(ui_voltmeter, UI_COMP_GAUGE_UNIT);
uic_boost_name = ui_comp_get_child(ui_boost, UI_COMP_GAUGE_NAME);
uic_boost_value = ui_comp_get_child(ui_boost, UI_COMP_GAUGE_VALUE);
uic_boost_unit = ui_comp_get_child(ui_boost, UI_COMP_GAUGE_UNIT);
uic_cts = ui_cts;
uic_cts_name = ui_comp_get_child(ui_cts, UI_COMP_GAUGE_NAME);
uic_cts_value = ui_comp_get_child(ui_cts, UI_COMP_GAUGE_VALUE);
uic_cts_unit = ui_comp_get_child(ui_cts, UI_COMP_GAUGE_UNIT);
uic_ait = ui_ait;
uic_ait_name = ui_comp_get_child(ui_ait, UI_COMP_GAUGE_NAME);
uic_ait_value = ui_comp_get_child(ui_ait, UI_COMP_GAUGE_VALUE);
uic_ait_unit = ui_comp_get_child(ui_ait, UI_COMP_GAUGE_UNIT);
uic_lambda = ui_lambda;
uic_lambda_name = ui_comp_get_child(ui_lambda, UI_COMP_GAUGE_NAME);
uic_lambda_value = ui_comp_get_child(ui_lambda, UI_COMP_GAUGE_VALUE);
uic_lambda_unit = ui_comp_get_child(ui_lambda, UI_COMP_GAUGE_UNIT);
uic_tach = ui_tach;
uic_tach_name = ui_comp_get_child(ui_tach, UI_COMP_GAUGE_NAME);
uic_tach_value = ui_comp_get_child(ui_tach, UI_COMP_GAUGE_VALUE);
uic_tach_unit = ui_comp_get_child(ui_tach, UI_COMP_GAUGE_UNIT);
uic_tach_shiftup = ui_shiftup;
uic_throttle = ui_throttle;
uic_throttle_name = ui_comp_get_child(ui_throttle, UI_COMP_GAUGE_NAME);
uic_throttle_value = ui_comp_get_child(ui_throttle, UI_COMP_GAUGE_VALUE);
uic_throttle_unit = ui_comp_get_child(ui_throttle, UI_COMP_GAUGE_UNIT);
uic_speed = ui_speed;
uic_speed_name = ui_comp_get_child(ui_speed, UI_COMP_GAUGE_NAME);
uic_speed_value = ui_comp_get_child(ui_speed, UI_COMP_GAUGE_VALUE);
uic_speed_unit = ui_comp_get_child(ui_speed, UI_COMP_GAUGE_UNIT);
uic_APC = ui_APC;
uic_APC_name = ui_comp_get_child(ui_APC, UI_COMP_GAUGE_NAME);
uic_APC_value = ui_comp_get_child(ui_APC, UI_COMP_GAUGE_VALUE);
uic_APC_unit = ui_comp_get_child(ui_APC, UI_COMP_GAUGE_UNIT);
uic_ignition = ui_ignition;
uic_ignition_name = ui_comp_get_child(ui_ignition, UI_COMP_GAUGE_NAME);
uic_ignition_value = ui_comp_get_child(ui_ignition, UI_COMP_GAUGE_VALUE);
uic_ignition_unit = ui_comp_get_child(ui_ignition, UI_COMP_GAUGE_UNIT);
uic_torque = ui_torque;
uic_torque_power = ui_comp_get_child(ui_torque, UI_COMP_GAUGE_NAME);
uic_torque_value = ui_comp_get_child(ui_torque, UI_COMP_GAUGE_VALUE);
uic_torque_unit = ui_comp_get_child(ui_torque, UI_COMP_GAUGE_UNIT);
uic_clock = ui_clock;
uic_clock_name = ui_comp_get_child(ui_clock, UI_COMP_GAUGE_NAME);
uic_clock_value = ui_comp_get_child(ui_clock, UI_COMP_GAUGE_VALUE);
uic_clock_unit = ui_comp_get_child(ui_clock, UI_COMP_GAUGE_UNIT);

}

void ui_SingleScr_screen_destroy(void)
{
   if (ui_SingleScr) lv_obj_del(ui_SingleScr);

// NULL screen variables
uic_SingleScr= NULL;
ui_SingleScr= NULL;
uic_voltmeter= NULL;
ui_voltmeter= NULL;
uic_voltmeter_name= NULL;
uic_voltmeter_value= NULL;
uic_voltmeter_unit= NULL;
ui_boost= NULL;
uic_boost_name= NULL;
uic_boost_value= NULL;
uic_boost_unit= NULL;
uic_cts= NULL;
ui_cts= NULL;
uic_cts_name= NULL;
uic_cts_value= NULL;
uic_cts_unit= NULL;
uic_ait= NULL;
ui_ait= NULL;
uic_ait_name= NULL;
uic_ait_value= NULL;
uic_ait_unit= NULL;
uic_lambda= NULL;
ui_lambda= NULL;
uic_lambda_name= NULL;
uic_lambda_value= NULL;
uic_lambda_unit= NULL;
uic_tach= NULL;
ui_tach= NULL;
uic_tach_name= NULL;
uic_tach_value= NULL;
uic_tach_unit= NULL;
uic_tach_shiftup= NULL;
ui_shiftup= NULL;
uic_throttle= NULL;
ui_throttle= NULL;
uic_throttle_name= NULL;
uic_throttle_value= NULL;
uic_throttle_unit= NULL;
uic_speed= NULL;
ui_speed= NULL;
uic_speed_name= NULL;
uic_speed_value= NULL;
uic_speed_unit= NULL;
uic_APC= NULL;
ui_APC= NULL;
uic_APC_name= NULL;
uic_APC_value= NULL;
uic_APC_unit= NULL;
uic_ignition= NULL;
ui_ignition= NULL;
uic_ignition_name= NULL;
uic_ignition_value= NULL;
uic_ignition_unit= NULL;
uic_torque= NULL;
ui_torque= NULL;
uic_torque_power= NULL;
uic_torque_value= NULL;
uic_torque_unit= NULL;
uic_clock= NULL;
ui_clock= NULL;
uic_clock_name= NULL;
uic_clock_value= NULL;
uic_clock_unit= NULL;

}
