// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *uic_StartupScr;
lv_obj_t *ui_StartupScr = NULL;lv_obj_t *ui_Trionic5 = NULL;lv_obj_t *ui_byMCS = NULL;lv_obj_t *ui_Spinner = NULL;
// event funtions
void ui_event_StartupScr( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      _ui_screen_change( &ui_DashDisplay, LV_SCR_LOAD_ANIM_FADE_ON, 250, 2000, &ui_DashDisplay_screen_init);
      _ui_screen_delete( &ui_StartupScr);
}
}

// build funtions

void ui_StartupScr_screen_init(void)
{
ui_StartupScr = lv_obj_create(NULL);
lv_obj_clear_flag( ui_StartupScr, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_StartupScr, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_StartupScr, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Trionic5 = lv_label_create(ui_StartupScr);
lv_obj_set_width( ui_Trionic5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Trionic5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Trionic5, 0 );
lv_obj_set_y( ui_Trionic5, -40 );
lv_obj_set_align( ui_Trionic5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Trionic5,"Trionic5");
lv_obj_set_style_text_color(ui_Trionic5, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Trionic5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Trionic5, &ui_font_GilMedium, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_byMCS = lv_label_create(ui_StartupScr);
lv_obj_set_width( ui_byMCS, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_byMCS, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_byMCS, 100 );
lv_obj_set_y( ui_byMCS, 30 );
lv_obj_set_align( ui_byMCS, LV_ALIGN_CENTER );
lv_label_set_text(ui_byMCS,"by MCS");
lv_obj_set_style_text_font(ui_byMCS, &ui_font_GilSm, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Spinner = lv_spinner_create(ui_StartupScr,1000,90);
lv_obj_set_width( ui_Spinner, 480);
lv_obj_set_height( ui_Spinner, 480);
lv_obj_set_align( ui_Spinner, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Spinner, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_arc_color(ui_Spinner, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Spinner, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_Spinner, lv_color_hex(0xA47E00), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Spinner, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_Spinner, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_StartupScr, ui_event_StartupScr, LV_EVENT_ALL, NULL);
uic_StartupScr = ui_StartupScr;

}

void ui_StartupScr_screen_destroy(void)
{
   if (ui_StartupScr) lv_obj_del(ui_StartupScr);

// NULL screen variables
uic_StartupScr= NULL;
ui_StartupScr= NULL;
ui_Trionic5= NULL;
ui_byMCS= NULL;
ui_Spinner= NULL;

}
