// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SINGLESCR_H
#define UI_SINGLESCR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SingleScr
extern void ui_SingleScr_screen_init(void);
extern void ui_SingleScr_screen_destroy(void);
extern void ui_event_SingleScr( lv_event_t * e);
extern lv_obj_t *ui_SingleScr;
extern lv_obj_t *ui_voltmeter;
extern lv_obj_t *ui_boost;
extern lv_obj_t *ui_cts;
extern lv_obj_t *ui_ait;
extern lv_obj_t *ui_lambda;
extern lv_obj_t *ui_tach;
extern lv_obj_t *ui_shiftup;
extern lv_obj_t *ui_throttle;
extern lv_obj_t *ui_speed;
extern lv_obj_t *ui_APC;
extern lv_obj_t *ui_ignition;
extern lv_obj_t *ui_torque;
extern lv_obj_t *ui_clock;
// CUSTOM VARIABLES
extern lv_obj_t *uic_SingleScr;
extern lv_obj_t *uic_voltmeter;
extern lv_obj_t *uic_voltmeter_name;
extern lv_obj_t *uic_voltmeter_value;
extern lv_obj_t *uic_voltmeter_unit;
extern lv_obj_t *uic_boost_name;
extern lv_obj_t *uic_boost_value;
extern lv_obj_t *uic_boost_unit;
extern lv_obj_t *uic_cts;
extern lv_obj_t *uic_cts_name;
extern lv_obj_t *uic_cts_value;
extern lv_obj_t *uic_cts_unit;
extern lv_obj_t *uic_ait;
extern lv_obj_t *uic_ait_name;
extern lv_obj_t *uic_ait_value;
extern lv_obj_t *uic_ait_unit;
extern lv_obj_t *uic_lambda;
extern lv_obj_t *uic_lambda_name;
extern lv_obj_t *uic_lambda_value;
extern lv_obj_t *uic_lambda_unit;
extern lv_obj_t *uic_tach;
extern lv_obj_t *uic_tach_name;
extern lv_obj_t *uic_tach_value;
extern lv_obj_t *uic_tach_unit;
extern lv_obj_t *uic_tach_shiftup;
extern lv_obj_t *uic_throttle;
extern lv_obj_t *uic_throttle_name;
extern lv_obj_t *uic_throttle_value;
extern lv_obj_t *uic_throttle_unit;
extern lv_obj_t *uic_speed;
extern lv_obj_t *uic_speed_name;
extern lv_obj_t *uic_speed_value;
extern lv_obj_t *uic_speed_unit;
extern lv_obj_t *uic_APC;
extern lv_obj_t *uic_APC_name;
extern lv_obj_t *uic_APC_value;
extern lv_obj_t *uic_APC_unit;
extern lv_obj_t *uic_ignition;
extern lv_obj_t *uic_ignition_name;
extern lv_obj_t *uic_ignition_value;
extern lv_obj_t *uic_ignition_unit;
extern lv_obj_t *uic_torque;
extern lv_obj_t *uic_torque_power;
extern lv_obj_t *uic_torque_value;
extern lv_obj_t *uic_torque_unit;
extern lv_obj_t *uic_clock;
extern lv_obj_t *uic_clock_name;
extern lv_obj_t *uic_clock_value;
extern lv_obj_t *uic_clock_unit;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

