// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *uic_UnitToggle;
lv_obj_t *uic_UnitsSetting;
lv_obj_t *uic_nightMode;
lv_obj_t *uic_SettingsScr;
lv_obj_t *ui_SettingsScr = NULL;lv_obj_t *ui_StyleSwitch = NULL;lv_obj_t *ui_styleToggle = NULL;lv_obj_t *ui_digitalLbl = NULL;lv_obj_t *ui_SwitchImpLbl1 = NULL;lv_obj_t *ui_Label5 = NULL;lv_obj_t *ui_DaySwitch = NULL;lv_obj_t *ui_nightMode = NULL;lv_obj_t *ui_SwitchMetricLbl1 = NULL;lv_obj_t *ui_SwitchImpLbl2 = NULL;lv_obj_t *ui_UnitSwitch = NULL;lv_obj_t *ui_unitToggle = NULL;lv_obj_t *ui_SwitchMetricLbl = NULL;lv_obj_t *ui_SwitchImpLbl = NULL;
// event funtions
void ui_event_SettingsScr( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
      _ui_screen_change( &ui_DashDisplay, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_DashDisplay_screen_init);
}
}

void ui_event_nightMode( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      toggleNightMode( e );
}
}

// build funtions

void ui_SettingsScr_screen_init(void)
{
ui_SettingsScr = lv_obj_create(NULL);
lv_obj_clear_flag( ui_SettingsScr, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SettingsScr, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SettingsScr, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_StyleSwitch = lv_obj_create(ui_SettingsScr);
lv_obj_remove_style_all(ui_StyleSwitch);
lv_obj_set_width( ui_StyleSwitch, 425);
lv_obj_set_height( ui_StyleSwitch, 50);
lv_obj_set_x( ui_StyleSwitch, 0 );
lv_obj_set_y( ui_StyleSwitch, -75 );
lv_obj_set_align( ui_StyleSwitch, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_StyleSwitch, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_styleToggle = lv_switch_create(ui_StyleSwitch);
lv_obj_set_width( ui_styleToggle, 80);
lv_obj_set_height( ui_styleToggle, 40);
lv_obj_set_align( ui_styleToggle, LV_ALIGN_CENTER );

ui_digitalLbl = lv_label_create(ui_StyleSwitch);
lv_obj_set_width( ui_digitalLbl, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_digitalLbl, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_digitalLbl, -100 );
lv_obj_set_y( ui_digitalLbl, 0 );
lv_obj_set_align( ui_digitalLbl, LV_ALIGN_CENTER );
lv_label_set_text(ui_digitalLbl,"Digital");
lv_obj_set_style_text_color(ui_digitalLbl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_digitalLbl, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_digitalLbl, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SwitchImpLbl1 = lv_label_create(ui_StyleSwitch);
lv_obj_set_width( ui_SwitchImpLbl1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SwitchImpLbl1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SwitchImpLbl1, 100 );
lv_obj_set_y( ui_SwitchImpLbl1, 0 );
lv_obj_set_align( ui_SwitchImpLbl1, LV_ALIGN_CENTER );
lv_label_set_text(ui_SwitchImpLbl1,"Analog");
lv_obj_set_style_text_font(ui_SwitchImpLbl1, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label5 = lv_label_create(ui_SettingsScr);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, 0 );
lv_obj_set_y( ui_Label5, -175 );
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"Settings");
lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label5, &ui_font_GilSm, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DaySwitch = lv_obj_create(ui_SettingsScr);
lv_obj_remove_style_all(ui_DaySwitch);
lv_obj_set_width( ui_DaySwitch, 425);
lv_obj_set_height( ui_DaySwitch, 50);
lv_obj_set_x( ui_DaySwitch, 0 );
lv_obj_set_y( ui_DaySwitch, 30 );
lv_obj_set_align( ui_DaySwitch, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_DaySwitch, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_nightMode = lv_switch_create(ui_DaySwitch);
lv_obj_set_width( ui_nightMode, 80);
lv_obj_set_height( ui_nightMode, 40);
lv_obj_set_align( ui_nightMode, LV_ALIGN_CENTER );

ui_SwitchMetricLbl1 = lv_label_create(ui_DaySwitch);
lv_obj_set_width( ui_SwitchMetricLbl1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SwitchMetricLbl1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SwitchMetricLbl1, -100 );
lv_obj_set_y( ui_SwitchMetricLbl1, 0 );
lv_obj_set_align( ui_SwitchMetricLbl1, LV_ALIGN_CENTER );
lv_label_set_text(ui_SwitchMetricLbl1,"Day");
lv_obj_set_style_text_color(ui_SwitchMetricLbl1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SwitchMetricLbl1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SwitchMetricLbl1, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SwitchImpLbl2 = lv_label_create(ui_DaySwitch);
lv_obj_set_width( ui_SwitchImpLbl2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SwitchImpLbl2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SwitchImpLbl2, 100 );
lv_obj_set_y( ui_SwitchImpLbl2, 0 );
lv_obj_set_align( ui_SwitchImpLbl2, LV_ALIGN_CENTER );
lv_label_set_text(ui_SwitchImpLbl2,"Night");
lv_obj_set_style_text_font(ui_SwitchImpLbl2, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_UnitSwitch = lv_obj_create(ui_SettingsScr);
lv_obj_remove_style_all(ui_UnitSwitch);
lv_obj_set_width( ui_UnitSwitch, 425);
lv_obj_set_height( ui_UnitSwitch, 50);
lv_obj_set_x( ui_UnitSwitch, 0 );
lv_obj_set_y( ui_UnitSwitch, 130 );
lv_obj_set_align( ui_UnitSwitch, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_UnitSwitch, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_unitToggle = lv_switch_create(ui_UnitSwitch);
lv_obj_set_width( ui_unitToggle, 80);
lv_obj_set_height( ui_unitToggle, 40);
lv_obj_set_align( ui_unitToggle, LV_ALIGN_CENTER );

ui_SwitchMetricLbl = lv_label_create(ui_UnitSwitch);
lv_obj_set_width( ui_SwitchMetricLbl, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SwitchMetricLbl, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SwitchMetricLbl, -100 );
lv_obj_set_y( ui_SwitchMetricLbl, 0 );
lv_obj_set_align( ui_SwitchMetricLbl, LV_ALIGN_CENTER );
lv_label_set_text(ui_SwitchMetricLbl,"Metric");
lv_obj_set_style_text_color(ui_SwitchMetricLbl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SwitchMetricLbl, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SwitchMetricLbl, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SwitchImpLbl = lv_label_create(ui_UnitSwitch);
lv_obj_set_width( ui_SwitchImpLbl, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SwitchImpLbl, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SwitchImpLbl, 100 );
lv_obj_set_y( ui_SwitchImpLbl, 0 );
lv_obj_set_align( ui_SwitchImpLbl, LV_ALIGN_CENTER );
lv_label_set_text(ui_SwitchImpLbl,"Imperial");
lv_obj_set_style_text_font(ui_SwitchImpLbl, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_nightMode, ui_event_nightMode, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SettingsScr, ui_event_SettingsScr, LV_EVENT_ALL, NULL);
uic_SettingsScr = ui_SettingsScr;
uic_nightMode = ui_nightMode;
uic_UnitsSetting = ui_UnitSwitch;
uic_UnitToggle = ui_unitToggle;

}

void ui_SettingsScr_screen_destroy(void)
{
   if (ui_SettingsScr) lv_obj_del(ui_SettingsScr);

// NULL screen variables
uic_SettingsScr= NULL;
ui_SettingsScr= NULL;
ui_StyleSwitch= NULL;
ui_styleToggle= NULL;
ui_digitalLbl= NULL;
ui_SwitchImpLbl1= NULL;
ui_Label5= NULL;
ui_DaySwitch= NULL;
uic_nightMode= NULL;
ui_nightMode= NULL;
ui_SwitchMetricLbl1= NULL;
ui_SwitchImpLbl2= NULL;
uic_UnitsSetting= NULL;
ui_UnitSwitch= NULL;
uic_UnitToggle= NULL;
ui_unitToggle= NULL;
ui_SwitchMetricLbl= NULL;
ui_SwitchImpLbl= NULL;

}
