// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_GAUGE_H
#define _UI_COMP_GAUGE_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Gauge
#define UI_COMP_GAUGE_GAUGE 0
#define UI_COMP_GAUGE_NAME 1
#define UI_COMP_GAUGE_VALUE 2
#define UI_COMP_GAUGE_UNIT 3
#define UI_COMP_GAUGE_MAXVALUE 4
#define _UI_COMP_GAUGE_NUM 5
lv_obj_t *ui_Gauge_create(lv_obj_t *comp_parent);
void ui_event_comp_Gauge_unit( lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
