// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_STARTUPSCR_H
#define UI_STARTUPSCR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_StartupScr
extern void ui_StartupScr_screen_init(void);
extern void ui_StartupScr_screen_destroy(void);
extern void ui_event_StartupScr( lv_event_t * e);
extern lv_obj_t *ui_StartupScr;
extern lv_obj_t *ui_Trionic5;
extern lv_obj_t *ui_byMCS;
extern lv_obj_t *ui_Spinner;
// CUSTOM VARIABLES
extern lv_obj_t *uic_StartupScr;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

