// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SETTINGSSCR_H
#define UI_SETTINGSSCR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SettingsScr
extern void ui_SettingsScr_screen_init(void);
extern void ui_SettingsScr_screen_destroy(void);
extern void ui_event_SettingsScr( lv_event_t * e);
extern lv_obj_t *ui_SettingsScr;
extern lv_obj_t *ui_StyleSwitch;
extern lv_obj_t *ui_styleToggle;
extern lv_obj_t *ui_digitalLbl;
extern lv_obj_t *ui_SwitchImpLbl1;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_DaySwitch;
extern void ui_event_nightMode( lv_event_t * e);
extern lv_obj_t *ui_nightMode;
extern lv_obj_t *ui_SwitchMetricLbl1;
extern lv_obj_t *ui_SwitchImpLbl2;
extern lv_obj_t *ui_UnitSwitch;
extern lv_obj_t *ui_unitToggle;
extern lv_obj_t *ui_SwitchMetricLbl;
extern lv_obj_t *ui_SwitchImpLbl;
// CUSTOM VARIABLES
extern lv_obj_t *uic_SettingsScr;
extern lv_obj_t *uic_nightMode;
extern lv_obj_t *uic_UnitsSetting;
extern lv_obj_t *uic_UnitToggle;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

